/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        vector<int> hash(26, 0);

        for(char ch : t) {
            hash[ch - 'a']++;            
        }
        for(char ch : s) {
            hash[ch - 'a']--;            
        }
        
        int ch;
        for(int index = 0; index < 26; ++index) {
            if(hash[index] == 1) {
                ch = index;
                break;
            }
        }

        return (char)(ch + 'a');
    }
};