/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

class Solution {
    public char findTheDifference(String s, String t) {
        int[] hash = new int[26];
        
        for(int index = 0; index < t.length(); ++index) {
            hash[t.charAt(index) - 'a']++;
            if(index < s.length()) {
                hash[s.charAt(index) - 'a']--;
            }
        }
        
        for(int index = 0; index < 26; ++index) {
            if(hash[index] == 1) {
                return (char)(index + 'a');
            }
        }
        
        return '1';
    }
}